<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="ELSystemTerminal" Id="{81ab68bf-673a-4607-9d5f-8e208f16d098}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_check'}
FUNCTION_BLOCK ELSystemTerminal //e.g. EL9410
VAR_OUTPUT CONSTANT
END_VAR
VAR_INPUT
END_VAR
VAR_OUTPUT	
	UsUndervoltage		 								AT  %I* : BOOL;
	UpUndervoltage										AT  %I* : BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	(* System terminal power status			*)
	(****************************************)
	
(* Work objects ****************************************)
;
(*******************************************************)
	]]></ST>
    </Implementation>
    <LineIds Name="ELSystemTerminal">
      <LineId Id="3" Count="5" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>