<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="WIN" Id="{a04b2460-c703-49ea-926b-64daf4c7ec79}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'monitoring' := 'variable'}
{attribute 'no_check'}
//if X between LO and HI then win = True else win = false
FUNCTION WIN : BOOL
VAR_INPUT
	X		: LREAL ;	
	LO		: LREAL ;
	HI		: LREAL ;
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[	(* window check 			  											ds	*)
	(****************************************************************************)
	(* if X between LO and HI then win = True else win = false					*)
	(****************************************************************************)


(* the current value of the window  *****************************************)
WIN 														:= 		X >= LO AND X <= HI;
(*****************************************************************************)]]></ST>
    </Implementation>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="WIN">
      <LineId Id="3" Count="7" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>