<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="EL9576" Id="{91b3d4b5-76e1-4aef-be35-d3492cdf7ca4}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_check'}
//EL Brake Chopper IOs
FUNCTION_BLOCK EL9576 
VAR_OUTPUT CONSTANT
END_VAR
VAR_INPUT
END_VAR
VAR_OUTPUT	
	Overtemperature									AT  %I* : BOOL;		//TRUE when there is an overtemperature on the PCB
	I2T_Error										AT  %I* : BOOL;		//TRUE when there is an overtemperature in the external resistor
	I2T_Warning										AT  %I* : BOOL;		//TRUE when the warning temperature threshold value from the CoE data has been exceeded
	Overvoltage										AT  %I* : BOOL;		//TRUE when the overvoltage threshold value has been exceeded
	Undervoltage									AT  %I* : BOOL;		//TRUE when the voltage has fallen below the undervoltage threshold value from the CoE data
	CopperOn										AT  %I* : BOOL;		//TRUE when the external resistor is active, i.e. electrical energy is being converted to thermal energy in the resistor
	OvercurrentProtection							AT  %I* : BOOL;		//TRUE when the external resistor is active, i.e. electrical energy is being converted to thermal energy in the resistor
	InputCycleCounter								AT  %I* : USINT;	//TRUE if the overcurrent or short-circuit detection of the EL9576 has been triggered. Otherwise the bit is permanently FALSE.
	DCLinkVoltage									AT  %I* : UDINT;	//External supply voltage in mV
	ResistorCurrent									AT  %I* : DINT;		//Current through the external resistor in mA
	DutyCycle										AT  %I* : USINT;	//Temporal utilization of the external resistor in the last 100 ms in %
	I2TLoadFactor									AT  %I* : USINT;	

	WcState											AT  %I* : BOOL;
	InputToggle										AT  %I* : BOOL;
	{attribute 'displaymode':='hex'}  
	State											AT  %I* : UINT;
	
END_VAR
VAR
{attribute 'hide'}
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Ax_BrakeCopperIO						*)
(****************************************)
	
(* Work objects ****************************************)
	;
(*******************************************************)
	]]></ST>
    </Implementation>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="EL9576">
      <LineId Id="3" Count="5" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>