<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FbBase" Id="{fa492ca6-037c-4b16-91aa-f2cc0fe6587b}" SpecialFunc="None">
    <Declaration><![CDATA[//Template for PlcOpen FB implementations - Extend final implementations from this FB
FUNCTION_BLOCK FbBase EXTENDS FbBaseOutputs
VAR_INPUT
	Execute													:	BOOL := FALSE; //The function block starts execution with a rising edge on this input  
END_VAR
VAR_IN_OUT
END_VAR
VAR_OUTPUT
END_VAR
VAR 
END_VAR
VAR
(* Cache ********************************************************************************)
	State													: INT := 0;

(* Trigger ******************************************************************************)
	rtExecute												:	R_TRIG;	

(* Dummys *******************************************************************************)

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <LineIds Name="FbBase">
      <LineId Id="90" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>