<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="InOut" Id="{17aa8cad-8612-4ded-9890-4df14d9b8014}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_check'}
FUNCTION_BLOCK InOut 
VAR_INPUT
	Q												AT  %Q*	:	BOOL; //Link to hardware output
END_VAR             								
VAR_OUTPUT          								
	In												AT  %I*	:	BOOL; //Link to hardware input
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="InOut">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>