<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="CAM" Id="{a0220706-a1c8-43d9-bdea-864c05bf8863}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'monitoring' := 'variable'}
{attribute 'no_check'}
//if x in setpoint +/- window then cam = true else cam = false
FUNCTION CAM : BOOL
VAR_INPUT
	X														: LREAL ; 	//value to be monitored
	SETP													: LREAL ;	//target value
	WINDOW													: LREAL ;	//tolerance zone
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* cam check				  											ds	*)
(****************************************************************************)
(* if x in setpoint +/- window then cam = true else cam = false				*)
(****************************************************************************)

(* the current value of the window  *****************************************)
CAM 														:=  X >= SETP - WINDOW AND X <= SETP + WINDOW ;
(****************************************************************************)]]></ST>
    </Implementation>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="CAM">
      <LineId Id="3" Count="6" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>