<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="EL1262_Base" Id="{8d89a8be-071a-466f-8821-50cf83fd473f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EL1262_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
	Input										AT %I*		:	BOOL;
{attribute 'displaymode':='binary'}
	Status										AT %I*		:	USINT;
	TimeLatchPos								AT %I*		:	T_DCTIME64;
	TimeLatchNeg								AT %I*		:	T_DCTIME64;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EL1262_Base">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>